// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC7Eba6H58BU3LTxxXmJRcofUN9FvE6zI',
    appId: '1:1094128746314:web:7ef3061ff9decba835cbb3',
    messagingSenderId: '1094128746314',
    projectId: 'sambadev-c3245',
    authDomain: 'sambadev-c3245.firebaseapp.com',
    storageBucket: 'sambadev-c3245.appspot.com',
    measurementId: 'G-3BJR2X7B7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCv3zJDfOynq9jAEkq9Bwf3_xUZjx2sZA',
    appId: '1:1094128746314:android:3574ee59fab636f335cbb3',
    messagingSenderId: '1094128746314',
    projectId: 'sambadev-c3245',
    storageBucket: 'sambadev-c3245.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAluAE62lb5GqFMA-GcHIsC94OOFmLuNj8',
    appId: '1:1094128746314:ios:fd69a7bc3844b88a35cbb3',
    messagingSenderId: '1094128746314',
    projectId: 'sambadev-c3245',
    storageBucket: 'sambadev-c3245.appspot.com',
    iosBundleId: 'com.example.sambadev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAluAE62lb5GqFMA-GcHIsC94OOFmLuNj8',
    appId: '1:1094128746314:ios:dec99bf35229176635cbb3',
    messagingSenderId: '1094128746314',
    projectId: 'sambadev-c3245',
    storageBucket: 'sambadev-c3245.appspot.com',
    iosBundleId: 'com.example.sambadev.RunnerTests',
  );
}
